# Generated by Django 5.2.17 on 2026-10-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("strength", models.IntegerField(default=0)),
                ("dexterity", models.IntegerField(default=0)),
                ("constitution", models.IntegerField(default=0)),
                ("intelligence", models.IntegerField(default=0)),
                ("wisdom", models.IntegerField(default=0)),
                ("charisma", models.IntegerField(default=0)),
                ("armor_class", models.IntegerField(default=0)),
                ("max_hp", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "character_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.character",
                    ),
                ),
            ],
            bases=("core.character",),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "character_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.character",
                    ),
                ),
            ],
            bases=("core.character",),
        ),
        migrations.CreateModel(
            name="CharacterEncounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_hp", models.IntegerField(default=0)),
                ("initiative", models.IntegerField(default=0)),
                ("x_pos", models.IntegerField(default=100)),
                ("y_pos", models.IntegerField(default=100)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_encounters",
                        to="core.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "characters",
                    models.ManyToManyField(
                        related_name="encounters",
                        through="core.CharacterEncounter",
                        to="core.character",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="characterencounter",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_encounters",
                to="core.encounter",
            ),
        ),
    ]
