# Generated by Django 5.2.17 on 2026-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterencounter",
            name="x_pos",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="characterencounter",
            name="y_pos",
            field=models.IntegerField(default=50),
        ),
    ]
