# Generated by Django 5.2.17 on 2026-10-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_encounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("strength", models.IntegerField(default=0)),
                ("dexterity", models.IntegerField(default=0)),
                ("constitution", models.IntegerField(default=0)),
                ("intelligence", models.IntegerField(default=0)),
                ("wisdom", models.IntegerField(default=0)),
                ("charisma", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="StarterItem",
        ),
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "character_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.character",
                    ),
                ),
            ],
            bases=("core.character",),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "character_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.character",
                    ),
                ),
            ],
            bases=("core.character",),
        ),
    ]
